---
# MS5.0 Floor Dashboard - Grafana Services Configuration
# Service and external access for Grafana with load balancing
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
    version: "10.0.0"
  annotations:
    description: "Grafana service for internal cluster access"
    managed-by: "ms5-devops-team"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: ms5-dashboard
    component: grafana
  # Session affinity for consistent connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour
---
# External service for Grafana with load balancer
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
    service-type: external
  annotations:
    description: "External service for Grafana with load balancer"
    managed-by: "ms5-devops-team"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "monitoring-subnet"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "ms5-production-rg"
spec:
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: ms5-dashboard
    component: grafana
  # Session affinity for consistent connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour
---
# ServiceMonitor for Grafana monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-monitor
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "ServiceMonitor for Grafana monitoring"
    managed-by: "ms5-devops-team"
spec:
  selector:
    matchLabels:
      app: ms5-dashboard
      component: grafana
  endpoints:
  - port: grafana
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    scheme: http
  namespaceSelector:
    matchNames:
    - monitoring
---
# PodMonitor for Grafana pod monitoring
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: grafana-pods
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "PodMonitor for Grafana pod monitoring"
    managed-by: "ms5-devops-team"
spec:
  selector:
    matchLabels:
      app: ms5-dashboard
      component: grafana
  podMetricsEndpoints:
  - port: grafana
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
    scheme: http
  namespaceSelector:
    matchNames:
    - monitoring
