---
# MS5.0 Floor Dashboard - Grafana Secrets Configuration
# Sensitive configuration data from Azure Key Vault integration
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "Grafana sensitive configuration and credentials"
    managed-by: "ms5-devops-team"
type: Opaque
data:
  # Base64 encoded values - these should be replaced with actual values from Azure Key Vault
  # Example: echo -n "your-secret-value" | base64
  GF_SECURITY_ADMIN_PASSWORD: ""  # Grafana admin password
  GF_SECURITY_SECRET_KEY: ""  # Grafana secret key for signing
  AZURE_AD_CLIENT_ID: ""  # Azure AD client ID for authentication
  AZURE_AD_CLIENT_SECRET: ""  # Azure AD client secret
  AZURE_AD_TENANT_ID: ""  # Azure AD tenant ID
  AZURE_SUBSCRIPTION_ID: ""  # Azure subscription ID
  POSTGRES_MONITORING_PASSWORD: ""  # PostgreSQL monitoring user password
  AZURE_LOG_ANALYTICS_WORKSPACE_ID: ""  # Azure Log Analytics workspace ID
  SMTP_PASSWORD: ""  # SMTP password for email notifications
  SLACK_WEBHOOK_URL: ""  # Slack webhook URL for notifications
  TEAMS_WEBHOOK_URL: ""  # Microsoft Teams webhook URL
  PAGERDUTY_SERVICE_KEY: ""  # PagerDuty service key
---
# Service Account for Grafana with proper RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "Service account for Grafana with Kubernetes API access"
    managed-by: "ms5-devops-team"
    azure.workload.identity/client-id: ""  # Azure AD client ID for workload identity
automountServiceAccountToken: true
---
# Role for Grafana within the monitoring namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "Role for Grafana within the monitoring namespace"
    managed-by: "ms5-devops-team"
rules:
# Namespace-specific resources
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
# ConfigMap access for datasources and dashboards
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames:
  - grafana-config
  - grafana-dashboards
  verbs: ["get", "list", "watch"]
---
# RoleBinding for Grafana within the monitoring namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
  annotations:
    description: "RoleBinding for Grafana within the monitoring namespace"
    managed-by: "ms5-devops-team"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: monitoring
---
# Azure Key Vault RBAC configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-azure-keyvault
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
    azure-integration: "keyvault"
  annotations:
    description: "ClusterRole for Grafana Azure Key Vault access"
    managed-by: "ms5-devops-team"
rules:
# Azure Key Vault secrets access
- apiGroups: ["external-secrets.io"]
  resources:
  - secretstores
  - externalsecrets
  - clustersecretstores
  verbs: ["get", "list", "watch"]
# Azure-specific resources
- apiGroups: ["aadpodidentity.k8s.io"]
  resources:
  - azureidentities
  - azureidentitybindings
  verbs: ["get", "list", "watch"]
---
# Azure Key Vault ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-azure-keyvault
  labels:
    app: ms5-dashboard
    component: grafana
    environment: production
    azure-integration: "keyvault"
  annotations:
    description: "ClusterRoleBinding for Grafana Azure Key Vault access"
    managed-by: "ms5-devops-team"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-azure-keyvault
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: monitoring
