apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-frontend-azure-cdn-monitoring
  namespace: ms5-frontend
  labels:
    app: ms5-frontend
    component: cdn
    tier: frontend
    environment: production
    deployment: aks
  annotations:
    description: "MS5.0 Floor Dashboard Azure CDN Monitoring Configuration for AKS"
    contact: "team@ms5floor.com"
    version: "1.0.0"
data:
  # Azure CDN Monitoring configuration
  cdn-monitoring.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ms5-frontend-cdn-monitoring
      namespace: ms5-frontend
      labels:
        app: ms5-frontend
        component: cdn
        tier: frontend
        environment: production
        deployment: aks
      annotations:
        description: "Azure CDN Monitoring Configuration for MS5.0 Dashboard"
        contact: "team@ms5floor.com"
        version: "1.0.0"
    data:
      monitoring-config.json: |
        {
          "monitoring": {
            "metrics": [
              {
                "name": "RequestCount",
                "aggregation": "Total",
                "interval": "PT1H"
              },
              {
                "name": "BytesSent",
                "aggregation": "Total",
                "interval": "PT1H"
              },
              {
                "name": "CacheHitRatio",
                "aggregation": "Average",
                "interval": "PT1H"
              },
              {
                "name": "OriginLatency",
                "aggregation": "Average",
                "interval": "PT1H"
              }
            ],
            "alerts": [
              {
                "name": "HighErrorRate",
                "condition": "error_rate > 5%",
                "severity": "High",
                "action": "NotifyTeam"
              },
              {
                "name": "LowCacheHitRatio",
                "condition": "cache_hit_ratio < 80%",
                "severity": "Medium",
                "action": "NotifyTeam"
              },
              {
                "name": "HighOriginLatency",
                "condition": "origin_latency > 1000ms",
                "severity": "High",
                "action": "NotifyTeam"
              }
            ]
          }
        }
  
  # Azure CDN Monitoring script
  cdn-monitor.py: |
    #!/usr/bin/env python3
    """
    CDN monitoring script for MS5.0 Dashboard
    """
    import json
    import requests
    import time
    from datetime import datetime
    
    def get_cdn_metrics():
        """Get CDN metrics from Azure"""
        try:
            # Azure CDN metrics endpoint
            cdn_url = "https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Cdn/profiles/{profile-name}/endpoints/{endpoint-name}/metrics"
            
            headers = {
                "Authorization": "Bearer {access-token}",
                "Content-Type": "application/json"
            }
            
            params = {
                "api-version": "2021-06-01",
                "metricnames": "RequestCount,BytesSent,CacheHitRatio",
                "aggregation": "Total",
                "interval": "PT1H",
                "startTime": "2023-01-01T00:00:00Z",
                "endTime": "2023-01-02T00:00:00Z"
            }
            
            response = requests.get(cdn_url, headers=headers, params=params, timeout=30)
            if response.status_code == 200:
                metrics = response.json()
                
                return {
                    "request_count": metrics.get("RequestCount", 0),
                    "bytes_sent": metrics.get("BytesSent", 0),
                    "cache_hit_ratio": metrics.get("CacheHitRatio", 0),
                    "timestamp": datetime.now().isoformat()
                }
        except Exception as e:
            print(f"Error getting CDN metrics: {e}")
            return None
    
    def send_metrics_to_prometheus(metrics):
        """Send CDN metrics to Prometheus"""
        try:
            prometheus_url = "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
            
            payload = {
                "metric": "cdn_request_count",
                "value": metrics["request_count"],
                "labels": {
                    "cdn_profile": "ms5-cdn-profile",
                    "endpoint": "ms5-cdn-endpoint"
                }
            }
            
            response = requests.post(prometheus_url, json=payload, timeout=5)
            if response.status_code == 200:
                print("CDN metrics sent to Prometheus successfully")
            else:
                print(f"Failed to send CDN metrics to Prometheus: {response.status_code}")
        except Exception as e:
            print(f"Error sending CDN metrics to Prometheus: {e}")
    
    def main():
        """Main monitoring loop"""
        while True:
            metrics = get_cdn_metrics()
            if metrics:
                print(json.dumps(metrics, indent=2))
                send_metrics_to_prometheus(metrics)
            
            time.sleep(3600)  # Check every hour
    
    if __name__ == "__main__":
        main()
  
  # Azure CDN Monitoring deployment
  cdn-monitor-deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cdn-monitor
      namespace: ms5-frontend
      labels:
        app: cdn-monitor
        component: monitoring
        tier: frontend
        environment: production
        deployment: aks
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cdn-monitor
      template:
        metadata:
          labels:
            app: cdn-monitor
        spec:
          containers:
          - name: cdn-monitor
            image: python:3.9-alpine
            command: ["python3", "/scripts/cdn-monitor.py"]
            volumeMounts:
            - name: cdn-script
              mountPath: /scripts
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: subscription-id
            - name: AZURE_RESOURCE_GROUP
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: resource-group
            - name: AZURE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: access-token
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
              limits:
                cpu: "50m"
                memory: "64Mi"
          volumes:
          - name: cdn-script
            configMap:
              name: cdn-monitoring-config
              defaultMode: 0755
