apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-frontend-azure-cdn-troubleshooting
  namespace: ms5-frontend
  labels:
    app: ms5-frontend
    component: cdn
    tier: frontend
    environment: production
    deployment: aks
  annotations:
    description: "MS5.0 Floor Dashboard Azure CDN Troubleshooting Configuration for AKS"
    contact: "team@ms5floor.com"
    version: "1.0.0"
data:
  # Azure CDN Troubleshooting configuration
  cdn-troubleshooting.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ms5-frontend-cdn-troubleshooting
      namespace: ms5-frontend
      labels:
        app: ms5-frontend
        component: cdn
        tier: frontend
        environment: production
        deployment: aks
      annotations:
        description: "Azure CDN Troubleshooting Configuration for MS5.0 Dashboard"
        contact: "team@ms5floor.com"
        version: "1.0.0"
    data:
      troubleshooting-config.json: |
        {
          "troubleshooting": {
            "endpoint": "ms5-cdn-endpoint",
            "profile": "ms5-cdn-profile",
            "resourceGroup": "ms5-rg",
            "subscription": "{subscription-id}",
            "commonIssues": [
              {
                "name": "HighErrorRate",
                "description": "CDN error rate is above 5%",
                "symptoms": [
                  "High 4xx/5xx error rates",
                  "Poor user experience",
                  "Increased support tickets"
                ],
                "causes": [
                  "Origin server issues",
                  "Configuration problems",
                  "Traffic spikes"
                ],
                "solutions": [
                  "Check origin server health",
                  "Review CDN configuration",
                  "Implement rate limiting",
                  "Scale origin resources"
                ]
              },
              {
                "name": "LowCacheHitRatio",
                "description": "CDN cache hit ratio is below 80%",
                "symptoms": [
                  "High origin bandwidth usage",
                  "Increased origin latency",
                  "Higher costs"
                ],
                "causes": [
                  "Short cache TTL",
                  "Dynamic content",
                  "Poor cache configuration"
                ],
                "solutions": [
                  "Increase cache TTL",
                  "Optimize cache rules",
                  "Implement cache warming",
                  "Review content types"
                ]
              },
              {
                "name": "HighOriginLatency",
                "description": "CDN origin latency is above 1000ms",
                "symptoms": [
                  "Slow page load times",
                  "Poor user experience",
                  "High bounce rates"
                ],
                "causes": [
                  "Origin server performance",
                  "Network issues",
                  "Geographic distance"
                ],
                "solutions": [
                  "Optimize origin server",
                  "Use multiple origins",
                  "Implement edge caching",
                  "Review network configuration"
                ]
              }
            ]
          }
        }
  
  # Azure CDN Troubleshooting monitoring
  cdn-troubleshooting-monitoring.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ms5-frontend-cdn-troubleshooting-monitoring
      namespace: ms5-frontend
      labels:
        app: ms5-frontend
        component: cdn
        tier: frontend
        environment: production
        deployment: aks
      annotations:
        description: "Azure CDN Troubleshooting Monitoring Configuration for MS5.0 Dashboard"
        contact: "team@ms5floor.com"
        version: "1.0.0"
    data:
      troubleshooting-monitoring.json: |
        {
          "monitoring": {
            "troubleshooting": "ms5-cdn-troubleshooting",
            "endpoint": "ms5-cdn-endpoint",
            "profile": "ms5-cdn-profile",
            "resourceGroup": "ms5-rg",
            "subscription": "{subscription-id}",
            "metrics": [
              {
                "name": "TroubleshootingIssues",
                "aggregation": "Total",
                "interval": "PT1H",
                "description": "Total number of troubleshooting issues detected"
              },
              {
                "name": "TroubleshootingResolved",
                "aggregation": "Total",
                "interval": "PT1H",
                "description": "Total number of troubleshooting issues resolved"
              },
              {
                "name": "TroubleshootingLatency",
                "aggregation": "Average",
                "interval": "PT1H",
                "description": "Average latency for troubleshooting resolution"
              }
            ],
            "alerts": [
              {
                "name": "HighTroubleshootingLatency",
                "condition": "troubleshooting_latency > 1000ms",
                "severity": "High",
                "action": "NotifyTeam",
                "description": "Troubleshooting resolution latency is above 1000ms"
              },
              {
                "name": "HighTroubleshootingErrorRate",
                "condition": "troubleshooting_error_rate > 5%",
                "severity": "High",
                "action": "NotifyTeam",
                "description": "Troubleshooting error rate is above 5%"
              }
            ]
          }
        }
  
  # Azure CDN Troubleshooting script
  cdn-troubleshooting.py: |
    #!/usr/bin/env python3
    """
    CDN troubleshooting script for MS5.0 Dashboard
    """
    import json
    import requests
    import time
    from datetime import datetime
    
    def get_cdn_troubleshooting():
        """Get CDN troubleshooting from Azure"""
        try:
            # Azure CDN troubleshooting endpoint
            troubleshooting_url = "https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Cdn/profiles/{profile-name}/endpoints/{endpoint-name}/troubleshooting"
            
            headers = {
                "Authorization": "Bearer {access-token}",
                "Content-Type": "application/json"
            }
            
            params = {
                "api-version": "2021-06-01",
                "metricnames": "RequestCount,BytesSent,CacheHitRatio",
                "aggregation": "Total",
                "interval": "PT1H",
                "startTime": "2023-01-01T00:00:00Z",
                "endTime": "2023-01-02T00:00:00Z"
            }
            
            response = requests.get(troubleshooting_url, headers=headers, params=params, timeout=30)
            if response.status_code == 200:
                troubleshooting = response.json()
                
                return {
                    "request_count": troubleshooting.get("RequestCount", 0),
                    "bytes_sent": troubleshooting.get("BytesSent", 0),
                    "cache_hit_ratio": troubleshooting.get("CacheHitRatio", 0),
                    "timestamp": datetime.now().isoformat()
                }
        except Exception as e:
            print(f"Error getting CDN troubleshooting: {e}")
            return None
    
    def send_troubleshooting_to_prometheus(troubleshooting):
        """Send CDN troubleshooting to Prometheus"""
        try:
            prometheus_url = "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
            
            payload = {
                "metric": "cdn_troubleshooting",
                "value": troubleshooting["request_count"],
                "labels": {
                    "cdn_profile": "ms5-cdn-profile",
                    "endpoint": "ms5-cdn-endpoint"
                }
            }
            
            response = requests.post(prometheus_url, json=payload, timeout=5)
            if response.status_code == 200:
                print("CDN troubleshooting sent to Prometheus successfully")
            else:
                print(f"Failed to send CDN troubleshooting to Prometheus: {response.status_code}")
        except Exception as e:
            print(f"Error sending CDN troubleshooting to Prometheus: {e}")
    
    def main():
        """Main troubleshooting loop"""
        while True:
            troubleshooting = get_cdn_troubleshooting()
            if troubleshooting:
                print(json.dumps(troubleshooting, indent=2))
                send_troubleshooting_to_prometheus(troubleshooting)
            
            time.sleep(3600)  # Check every hour
    
    if __name__ == "__main__":
        main()
  
  # Azure CDN Troubleshooting deployment
  cdn-troubleshooting-deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cdn-troubleshooting
      namespace: ms5-frontend
      labels:
        app: cdn-troubleshooting
        component: monitoring
        tier: frontend
        environment: production
        deployment: aks
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cdn-troubleshooting
      template:
        metadata:
          labels:
            app: cdn-troubleshooting
        spec:
          containers:
          - name: cdn-troubleshooting
            image: python:3.9-alpine
            command: ["python3", "/scripts/cdn-troubleshooting.py"]
            volumeMounts:
            - name: troubleshooting-script
              mountPath: /scripts
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: subscription-id
            - name: AZURE_RESOURCE_GROUP
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: resource-group
            - name: AZURE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: access-token
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
              limits:
                cpu: "50m"
                memory: "64Mi"
          volumes:
          - name: troubleshooting-script
            configMap:
              name: cdn-troubleshooting-config
              defaultMode: 0755
