# MS5.0 Floor Dashboard - Frontend Service Account
# 
# This service account provides:
# - RBAC permissions for frontend operations
# - Security context for pod execution
# - Access to required Kubernetes resources
# - Monitoring and logging permissions

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms5-frontend-service-account
  namespace: ms5-floor-dashboard
  labels:
    app: ms5-frontend
    component: frontend
    environment: production
    platform: kubernetes
    version: "1.0.0"
  annotations:
    description: "MS5.0 Frontend Service Account"
    last-updated: "2024-01-01T00:00:00Z"
automountServiceAccountToken: true
---
# Role for frontend operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms5-frontend-role
  namespace: ms5-floor-dashboard
  labels:
    app: ms5-frontend
    component: frontend
    environment: production
    platform: kubernetes
    version: "1.0.0"
  annotations:
    description: "MS5.0 Frontend Role"
    last-updated: "2024-01-01T00:00:00Z"
rules:
# ConfigMap access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["ms5-frontend-config"]

# Secret access
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["ms5-frontend-secrets"]

# Pod access for monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Service access
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

# Endpoints access
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

# Events access for monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]

# PersistentVolumeClaims access
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

# NetworkPolicies access
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]

# Ingress access
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

# HorizontalPodAutoscaler access
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]

# VerticalPodAutoscaler access
- apiGroups: ["autoscaling.k8s.io"]
  resources: ["verticalpodautoscalers"]
  verbs: ["get", "list", "watch"]

# PodDisruptionBudget access
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]

# Deployment access
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

# ReplicaSet access
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]

# StatefulSet access
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]

# DaemonSet access
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]
---
# ClusterRole for cross-namespace access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ms5-frontend-cluster-role
  labels:
    app: ms5-frontend
    component: frontend
    environment: production
    platform: kubernetes
    version: "1.0.0"
  annotations:
    description: "MS5.0 Frontend Cluster Role"
    last-updated: "2024-01-01T00:00:00Z"
rules:
# Node access for monitoring
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Namespace access
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

# PersistentVolumes access
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

# StorageClasses access
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

# CustomResourceDefinitions access
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

# APIServices access
- apiGroups: ["apiregistration.k8s.io"]
  resources: ["apiservices"]
  verbs: ["get", "list", "watch"]

# MutatingWebhookConfigurations access
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch"]

# ValidatingWebhookConfigurations access
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "list", "watch"]

# ClusterRoles access
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get", "list", "watch"]

# ClusterRoleBindings access
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["get", "list", "watch"]

# Roles access
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["get", "list", "watch"]

# RoleBindings access
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "list", "watch"]

# ServiceAccounts access
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]

# SecurityContextConstraints access (OpenShift)
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["get", "list", "watch"]

# PodSecurityPolicies access
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["get", "list", "watch", "use"]
---
# RoleBinding for namespace-level permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms5-frontend-role-binding
  namespace: ms5-floor-dashboard
  labels:
    app: ms5-frontend
    component: frontend
    environment: production
    platform: kubernetes
    version: "1.0.0"
  annotations:
    description: "MS5.0 Frontend Role Binding"
    last-updated: "2024-01-01T00:00:00Z"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ms5-frontend-role
subjects:
- kind: ServiceAccount
  name: ms5-frontend-service-account
  namespace: ms5-floor-dashboard
---
# ClusterRoleBinding for cluster-level permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ms5-frontend-cluster-role-binding
  labels:
    app: ms5-frontend
    component: frontend
    environment: production
    platform: kubernetes
    version: "1.0.0"
  annotations:
    description: "MS5.0 Frontend Cluster Role Binding"
    last-updated: "2024-01-01T00:00:00Z"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ms5-frontend-cluster-role
subjects:
- kind: ServiceAccount
  name: ms5-frontend-service-account
  namespace: ms5-floor-dashboard
