---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-app-config
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: config
data:
  # Application Settings
  APP_NAME: "MS5.0 Floor Dashboard API"
  VERSION: "1.0.0"
  ENVIRONMENT: "production"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  
  # Security Settings
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # CORS Settings
  ALLOWED_ORIGINS: "https://ms5-dashboard.company.com,https://ms5-api.company.com"
  ALLOWED_HOSTS: "ms5-dashboard.company.com,ms5-api.company.com"
  
  # Database Settings
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "40"
  DATABASE_ECHO: "false"
  
  # WebSocket Settings
  WEBSOCKET_HEARTBEAT_INTERVAL: "30"
  WEBSOCKET_MAX_CONNECTIONS: "1000"
  
  # Production Settings
  PRODUCTION_LINE_POLL_INTERVAL: "5"
  OEE_CALCULATION_INTERVAL: "60"
  DOWNTIME_DETECTION_THRESHOLD: "30"
  
  # File Upload Settings
  MAX_FILE_SIZE: "10485760"  # 10MB
  UPLOAD_DIRECTORY: "uploads"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,application/pdf"
  
  # Email Settings
  SMTP_PORT: "587"
  SMTP_USE_TLS: "true"
  
  # Monitoring Settings
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  
  # Feature Flags
  ENABLE_OFFLINE_MODE: "true"
  ENABLE_PREDICTIVE_MAINTENANCE: "false"
  ENABLE_AI_INSIGHTS: "false"
  
  # Integration Settings
  PLC_POLL_INTERVAL: "1"
  PLC_TIMEOUT: "5"
  PLC_RETRY_ATTEMPTS: "3"
  
  # Report Settings
  REPORT_TEMPLATE_DIR: "templates/reports"
  REPORT_OUTPUT_DIR: "reports"
  REPORT_RETENTION_DAYS: "90"
  
  # Andon Settings
  ANDON_ESCALATION_LEVELS: "3"
  ANDON_ACKNOWLEDGMENT_TIMEOUT: "300"
  ANDON_RESOLUTION_TIMEOUT: "1800"
  
  # Quality Settings
  QUALITY_CHECK_INTERVAL: "60"
  DEFECT_ESCALATION_THRESHOLD: "5"
  
  # Maintenance Settings
  MAINTENANCE_REMINDER_DAYS: "7"
  MAINTENANCE_OVERDUE_DAYS: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-database-config
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: database
data:
  # PostgreSQL Configuration
  POSTGRES_DB: "factory_telemetry"
  POSTGRES_USER: "ms5_user"
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
  POSTGRES_REPLICATION_USER: "ms5_replication_user"
  
  # TimescaleDB Configuration
  TIMESCALEDB_VERSION: "latest-pg15"
  
  # Database Performance Settings
  shared_buffers: "256MB"
  effective_cache_size: "1GB"
  maintenance_work_mem: "64MB"
  checkpoint_completion_target: "0.9"
  wal_buffers: "16MB"
  default_statistics_target: "100"
  random_page_cost: "1.1"
  effective_io_concurrency: "200"
  
  # Connection Settings
  max_connections: "200"
  shared_preload_libraries: "timescaledb"
  
  # Logging Settings
  log_destination: "stderr"
  logging_collector: "on"
  log_directory: "pg_log"
  log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
  log_rotation_age: "1d"
  log_rotation_size: "100MB"
  log_min_duration_statement: "1000"
  log_line_prefix: "%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h "
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-redis-config
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
data:
  redis.conf: |
    # Redis Configuration for MS5.0 Dashboard
    
    # Network
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # General
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    
    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-ping-replica-period 10
    repl-timeout 60
    repl-disable-tcp-nodelay no
    repl-backlog-size 1mb
    repl-backlog-ttl 3600
    
    # Security
    requirepass ${REDIS_PASSWORD}
    
    # Memory Management
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    
    # Append Only File
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
    
    # Slow Log
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Latency Monitoring
    latency-monitor-threshold 100
    
    # Event Notification
    notify-keyspace-events ""
    
    # Advanced Config
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    dynamic-hz yes
    aof-rewrite-incremental-fsync yes
    rdb-save-incremental-fsync yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms5-minio-config
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: minio
data:
  # MinIO Configuration
  MINIO_ROOT_USER: "ms5_minio_user"
  MINIO_CONSOLE_ADDRESS: ":9001"
  
  # Bucket Policies
  bucket-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": ["*"]
          },
          "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
          ],
          "Resource": [
            "arn:aws:s3:::ms5-uploads/*",
            "arn:aws:s3:::ms5-reports/*",
            "arn:aws:s3:::ms5-backups/*"
          ]
        }
      ]
    }
