---
apiVersion: v1
kind: Secret
metadata:
  name: kv-ms5-prod-uksouth-secret
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: keyvault
type: Opaque
data:
  clientid: <base64-encoded-client-id>
  clientsecret: <base64-encoded-client-secret>
---
apiVersion: v1
kind: SecretProviderClass
metadata:
  name: ms5-keyvault-secrets
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<managed-identity-id>"
    keyvaultName: "kv-ms5-prod-uksouth"
    tenantId: "<tenant-id>"
    objects: |
      array:
        - |
          objectName: ms5-database-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: ms5-redis-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: ms5-minio-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: ms5-jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: ms5-smtp-credentials
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: ms5-keyvault-secrets
    type: Opaque
    data:
    - objectName: ms5-database-password
      key: DATABASE_PASSWORD
    - objectName: ms5-redis-password
      key: REDIS_PASSWORD
    - objectName: ms5-minio-password
      key: MINIO_ROOT_PASSWORD
    - objectName: ms5-jwt-secret
      key: JWT_SECRET
    - objectName: ms5-smtp-credentials
      key: SMTP_CREDENTIALS
