---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: primary
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary-headless
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: primary
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: replica
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica-headless
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: replica
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: redis-readonly
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: readonly
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: redis-monitoring
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: redis
    role: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ms5-dashboard
    component: redis
