---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: minio
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: ms5-dashboard
    component: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: minio
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: ms5-dashboard
    component: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-loadbalancer
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: ms5-dashboard
    component: minio
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
---
apiVersion: v1
kind: Service
metadata:
  name: minio-monitoring
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: minio
    role: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  selector:
    app: ms5-dashboard
    component: minio
