---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: prometheus
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: prometheus
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-monitoring
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: prometheus
    role: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: prometheus
