---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: ms5-dashboard
    component: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-headless
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: grafana
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: ms5-dashboard
    component: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: ms5-dashboard
    component: grafana
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-monitoring
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: grafana
    role: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app: ms5-dashboard
    component: grafana
