---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: alertmanager
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-loadbalancer
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: alertmanager
spec:
  type: LoadBalancer
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: alertmanager
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-monitoring
  namespace: ms5-production
  labels:
    app: ms5-dashboard
    component: alertmanager
    role: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: ms5-dashboard
    component: alertmanager
