---
# MS5.0 Floor Dashboard - AlertManager Secrets Configuration
# Sensitive configuration data from Azure Key Vault integration
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
  annotations:
    description: "AlertManager sensitive configuration and credentials"
    managed-by: "ms5-devops-team"
type: Opaque
data:
  # Base64 encoded values - these should be replaced with actual values from Azure Key Vault
  # Example: echo -n "your-secret-value" | base64
  SMTP_PASSWORD: ""  # SMTP password for email notifications
  SLACK_WEBHOOK_URL: ""  # Slack webhook URL for notifications
  TEAMS_WEBHOOK_URL: ""  # Microsoft Teams webhook URL
  PAGERDUTY_CRITICAL_SERVICE_KEY: ""  # PagerDuty critical service key
  PAGERDUTY_HIGH_PRIORITY_SERVICE_KEY: ""  # PagerDuty high priority service key
  WEBHOOK_URL: ""  # Generic webhook URL
  WEBHOOK_BEARER_TOKEN: ""  # Webhook bearer token
  AZURE_COMM_SERVICES_ENDPOINT: ""  # Azure Communication Services endpoint
  AZURE_COMM_SERVICES_ACCESS_KEY: ""  # Azure Communication Services access key
  CRITICAL_ALERT_EMAIL: ""  # Critical alert email address
  HIGH_PRIORITY_ALERT_EMAIL: ""  # High priority alert email address
  MEDIUM_PRIORITY_ALERT_EMAIL: ""  # Medium priority alert email address
  LOW_PRIORITY_ALERT_EMAIL: ""  # Low priority alert email address
  BACKEND_TEAM_EMAIL: ""  # Backend team email address
  DATABASE_TEAM_EMAIL: ""  # Database team email address
  CACHE_TEAM_EMAIL: ""  # Cache team email address
  CELERY_TEAM_EMAIL: ""  # Celery team email address
  STORAGE_TEAM_EMAIL: ""  # Storage team email address
  PRODUCTION_TEAM_EMAIL: ""  # Production team email address
  MAINTENANCE_TEAM_EMAIL: ""  # Maintenance team email address
---
# Service Account for AlertManager with proper RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
  annotations:
    description: "Service account for AlertManager with Kubernetes API access"
    managed-by: "ms5-devops-team"
    azure.workload.identity/client-id: ""  # Azure AD client ID for workload identity
automountServiceAccountToken: true
---
# Role for AlertManager within the monitoring namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
  annotations:
    description: "Role for AlertManager within the monitoring namespace"
    managed-by: "ms5-devops-team"
rules:
# Namespace-specific resources
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
# ConfigMap access for configuration
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames:
  - alertmanager-config
  verbs: ["get", "list", "watch"]
---
# RoleBinding for AlertManager within the monitoring namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
  annotations:
    description: "RoleBinding for AlertManager within the monitoring namespace"
    managed-by: "ms5-devops-team"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alertmanager
subjects:
- kind: ServiceAccount
  name: alertmanager
  namespace: monitoring
---
# Azure Key Vault RBAC configuration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alertmanager-azure-keyvault
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
    azure-integration: "keyvault"
  annotations:
    description: "ClusterRole for AlertManager Azure Key Vault access"
    managed-by: "ms5-devops-team"
rules:
# Azure Key Vault secrets access
- apiGroups: ["external-secrets.io"]
  resources:
  - secretstores
  - externalsecrets
  - clustersecretstores
  verbs: ["get", "list", "watch"]
# Azure-specific resources
- apiGroups: ["aadpodidentity.k8s.io"]
  resources:
  - azureidentities
  - azureidentitybindings
  verbs: ["get", "list", "watch"]
---
# Azure Key Vault ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alertmanager-azure-keyvault
  labels:
    app: ms5-dashboard
    component: alertmanager
    environment: production
    azure-integration: "keyvault"
  annotations:
    description: "ClusterRoleBinding for AlertManager Azure Key Vault access"
    managed-by: "ms5-devops-team"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alertmanager-azure-keyvault
subjects:
- kind: ServiceAccount
  name: alertmanager
  namespace: monitoring
